---
services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo18
      - POSTGRES_PASSWORD=odoo18@2030
      - POSTGRES_DB=postgres
    restart: always
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432/tcp
    networks:
      - odoo_network

  odoo18:
    image: odoo:18
    user: root
    depends_on:
      - db
    ports:
      - "10069:8069"
      - "10071:8071"
      - "10072:8072"
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo18
      - PASSWORD=odoo18@2030
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge
