---
name: odoo

services:
  db:
    image: postgres:16
    container_name: odoo_db
    user: root
    environment:
      - POSTGRES_HOST="10.24.24.100"
      - POSTGRES_USER=odoo18
      - POSTGRES_PASSWORD=odoo18@2030
      - POSTGRES_DB=postgres
    restart: always
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - odoo_network

  odoo:
    image: odoo:18
    container_name: odoo_app
    user: root
    depends_on:
      - db
    ports:
      - 8069:8069
      - 8071:8071
      - 8072:8072
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo18
      - PASSWORD=odoo18@2030
    volumes:
#      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge
    name: odoo_network
#    external: true
