version: '2'
services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo18
      - POSTGRES_PASSWORD=odoo18@2030
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo18:
    image: odoo:18
    user: root
    depends_on:
      - db
    ports:
      - "10069:8069"
      - "10071:8071"
      - "10072:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo18
      - PASSWORD=odoo18@2030
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      - ./wait-for-psql.py
      - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
    
